import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import { regular, bold, poppins, medium } from "@/lib/fonts";
import { AuthProvider } from "@/lib/auth/AuthContext";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${medium.variable} antialiased`}
      >
         <AuthProvider>
      
         {children}
         </AuthProvider>
        
      </body>
    </html>
  );
}
